[tool.poetry]
name = "vectorsearch-applications"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
llama-hub = "0.0.72"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
